### ISSUE TITLE
Join: accept an iterable structure

### ISSUE THREAD

**Issue by StevenBlack** [devHammed/HUI.js#2]
In the doc page, we see:

    container.Join(header); container.Join(main); container.Join(footer);

This would be cool: Join() could detect an array and, if so, spin it.

    container.Join([header, main, footer]);

Additionally, if Join returns a self, we could chain.

    container.Join(header).Join(main).Join(footer);

**Comment by devhammed** [comment]
Fixed!, you can now chain methods Child() and Join().

**Comment by devhammed** [comment]
Done! You can now pass Single Element or Elements Array to Join(). @stevenblack
